version: "3.8"

services:
  php:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    environment:
      PHP_IDE_CONFIG: "serverName=localhost"
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
    networks:
      - backend
    depends_on:
      - db
    extra_hosts:
      - host.docker.internal:host-gateway

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: backend
      MYSQL_USER: user
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    networks:
      - backend

networks:
  backend:
